### ISSUE TITLE
Null safety support?

### ISSUE THREAD

**Issue by AscentionOne** [RayOkaah/woocommerce#52]
Hi is there any plane of Null-Safety support? Thank you!

**Comment by Mayb3Nots** [comment]
I have updated to null safety. you can use this in ur pubsbec.yaml

```
 woocommerce:
    git:
      url: https://github.com/Mayb3Nots/woocommerce
      ref: master
```
